import {
  ProposalDraftStatus,
  ProposalStatus,
} from '@/type/proposal/proposal-status'

enum SubscriptionPaymentStatus {
  PENDING = 'Pending',
  SUCCEEDED = 'Succeeded',
  FAILED = 'Failed',
}

export const mockMyProposals = [
  {
    id: '1',
    title: 'Proposal 1',
    status: ProposalStatus.PENDING,
  },
  {
    id: '2',
    title: 'Proposal 2',
    status: ProposalStatus.REVIEW,
  },
  {
    id: '3',
    title: 'Proposal 3',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '4',
    title: 'Proposal 4',
    status: ProposalStatus.PUBLISHED,
  },
  {
    id: '5',
    title: 'Proposal 5',
    status: ProposalStatus.REJECTED,
  },
]

export const mockCandidateProposals = [
  {
    id: '1',
    firstName: 'Luis',
    lastName: 'Berumen',
    email: 'luis@luis.com',
    status: ProposalStatus.PENDING,
  },
  {
    id: '2',
    firstName: 'Seol',
    lastName: 'Kim',
    email: 'seol@seol.com',
    status: ProposalStatus.REVIEW,
  },
  {
    id: '3',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@john.com',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '4',
    firstName: 'Nara',
    lastName: 'Park',
    email: 'nara@nara.com',
    status: ProposalStatus.REJECTED,
  },
  {
    id: '5',
    firstName: 'Sam',
    lastName: 'Hong',
    email: 'sam@sam.com',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '6',
    firstName: 'Cody',
    lastName: 'Smith',
    email: 'cody@cody.com',
    status: ProposalStatus.REJECTED,
  },
  {
    id: '7',
    firstName: 'Kyla',
    lastName: 'Doe',
    email: 'kyla@kyla.com',
    status: ProposalStatus.REVIEW,
  },
  {
    id: '8',
    firstName: 'Jane',
    lastName: 'Kim',
    email: 'jane@jane.com',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '9',
    firstName: 'Chris',
    lastName: 'Smith',
    email: 'chris@chris.com',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '10',
    firstName: 'Jordan',
    lastName: 'Doe',
    email: 'jordan@jordan.com',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '11',
    firstName: 'Jane',
    lastName: 'Kim',
    email: 'jane@jane.com',
    status: ProposalStatus.APPROVED,
  },
  {
    id: '12',
    firstName: 'Sofia',
    lastName: 'Smith',
    email: 'sofia@sofia.com',
    status: ProposalStatus.REJECTED,
  },
]

export const mockCandidateDraftProposals = [
  {
    id: '1',
    firstName: 'Luis',
    lastName: 'Berumen',
    email: 'luis@luis.com',
    status: ProposalDraftStatus.DRAFT_PENDING,
  },
  {
    id: '2',
    firstName: 'Seol',
    lastName: 'Kim',
    email: 'seol@seol.com',
    status: ProposalDraftStatus.DRAFT_REVIEW,
  },
  {
    id: '3',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@john.com',
    status: ProposalDraftStatus.DRAFT_PENDING,
  },
  {
    id: '4',
    firstName: 'Nara',
    lastName: 'Park',
    email: 'nara@nara.com',
    status: ProposalDraftStatus.DRAFT_REJECTED,
  },
  {
    id: '5',
    firstName: 'Sam',
    lastName: 'Hong',
    email: 'sam@sam.com',
    status: ProposalDraftStatus.DRAFT_APPROVED,
  },
  {
    id: '6',
    firstName: 'Cody',
    lastName: 'Smith',
    email: 'cody@cody.com',
    status: ProposalDraftStatus.DRAFT_REJECTED,
  },
  {
    id: '7',
    firstName: 'Kyla',
    lastName: 'Doe',
    email: 'kyla@kyla.com',
    status: ProposalDraftStatus.DRAFT_REVIEW,
  },
  {
    id: '8',
    firstName: 'Jane',
    lastName: 'Kim',
    email: 'jane@jane.com',
    status: ProposalDraftStatus.DRAFT_APPROVED,
  },
  {
    id: '9',
    firstName: 'Chris',
    lastName: 'Smith',
    email: 'chris@chris.com',
    status: ProposalDraftStatus.DRAFT_APPROVED,
  },
  {
    id: '10',
    firstName: 'Jordan',
    lastName: 'Doe',
    email: 'jordan@jordan.com',
    status: ProposalDraftStatus.DRAFT_APPROVED,
  },
  {
    id: '11',
    firstName: 'Jane',
    lastName: 'Kim',
    email: 'jane@jane.com',
    status: ProposalDraftStatus.DRAFT_REJECTED,
  },
  {
    id: '12',
    firstName: 'Sofia',
    lastName: 'Smith',
    email: 'sofia@sofia.com',
    status: ProposalDraftStatus.DRAFT_REJECTED,
  },
]

export const mockInquiryDetail = [
  {
    id: '1',
    name: 'Apple',
    email: 'apple@apple.com',
    firstName: 'Jone',
    lastName: 'Doe',
    role: 'Manager',
    companySize: 3,
    numOfHires: 3,
    location: {
      country: 'Canada',
      province: 'Alberta',
      city: 'Calgary',
      address: '123 Main St',
    },
    note: 'Hello, I am Apple.I am AppleI am AppleI am AppleI am AppleI am AppleI am AppleI am AppleI am AppleI am AppleI am Apple',
    subscription: 'company-aether',
    status: ProposalStatus.PENDING,
    subscriptionPaymentStatus: SubscriptionPaymentStatus.PENDING,
  },
  {
    id: '2',
    name: 'Samsung',
    email: 'samsung@samsung.com',
    firstName: 'Jane',
    lastName: 'Kim',
    role: 'Manager',
    companySize: 4,
    numOfHires: 4,
    location: {
      country: 'Canada',
      province: 'Alberta',
      city: 'Calgary',
      address: '123 Main St',
    },
    note: 'Hello, I am Samsung',
    subscription: 'company-aether',
    status: ProposalStatus.PENDING,
    subscriptionPaymentStatus: SubscriptionPaymentStatus.PENDING,
  },
  {
    id: '3',
    name: 'Google',
    email: 'google@google.com',
    firstName: 'Chris',
    lastName: 'Smith',
    role: 'Manager',
    companySize: 5,
    numOfHires: 5,
    location: {
      country: 'Canada',
      province: 'Alberta',
      city: 'Calgary',
      address: '123 Main St',
    },
    note: 'Hello, I am Google',
    subscription: 'company-aether',
    status: ProposalStatus.APPROVED,
    subscriptionPaymentStatus: SubscriptionPaymentStatus.SUCCEEDED,
  },
]
